### ISSUE TITLE
Selection toolbar didn't work after migrate null safe

### ISSUE THREAD

**Issue by theacheng** [singerdmx/flutter-quill#119]
There might be some code break after migration to null safe as I try to track it:
1. A commit before migrate:
```yaml
flutter_quill:
  git:
    url: https://github.com/singerdmx/flutter-quill.git
    ref: dda5805935568d42b71a1a1faf7fbdf078d72633
```

Selection toolbar work.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/29684683/112725385-8c5a1d80-8f4a-11eb-8895-74cf722e8d7a.png">

2. A commit after migrate:
```yaml
flutter_quill:
  git:
    url: https://github.com/singerdmx/flutter-quill.git
    ref: 60514cbd24fbde3a4500ae04b930a039ee5851f4
```

Selection toolbar doesn't work.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/29684683/112725610-b233f200-8f4b-11eb-83b8-3bcedba3f68f.png">
