### ISSUE TITLE
Build Problems With Flutter_Quill

### ISSUE THREAD

**Issue by codenfast** [singerdmx/flutter-quill#144]
Hi All,
I have a problem, and i cannot found any reasonable solution.
My currently pubspec.yaml status is

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  shared_preferences: ^2.0.5
  webview_flutter: ^1.0.7
  font_awesome_flutter: ^9.0.0
  http: ^0.13.1
  intl: ^0.17.0
  focused_menu: ^1.0.5
  path_provider: ^2.0.1
  open_file: ^3.1.0
  flutter_quill: ^1.1.8
  universal_html: ^2.0.8
```

 Only added flutter quill and universal_html,
But now, i cannot build up project, giving to me an error, there is no implementation of "TextSelectionDelegate.userUpdateTextEditingValue" method.
Platform -> Android 11 (emulator), Android 5 (real device)
Problem occurs in Gradle Build,
Stack is;
```
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.1.8/lib/widgets/raw_editor.dart:95:7: Error: The non-abstract class 'RawEditorState' is missing implementations for these members:
 - TextSelectionDelegate.userUpdateTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
class RawEditorState extends EditorState
      ^^^^^^^^^^^^^^
/E:/flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextSelectionDelegate.userUpdateTextEditingValue' is defined here.
  void userUpdateTextEditingValue(TextEditingValue value, SelectionChangedCause cause);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_quill-1.1.8/lib/widgets/raw_editor.dart:1025:8: Error: The method 'RawEditorState.hideToolbar' has fewer positional arguments than those of overridden method 'TextSelectionDelegate.hideToolbar'.
  void hideToolbar() {
       ^
/E:/flutter/packages/flutter/lib/src/services/text_input.dart:829:8: Context: This is the overridden method ('hideToolbar').
  void hideToolbar([bool hideHandles = true]);
       ^
```

Usage;
```
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_quill/widgets/controller.dart';
import 'package:flutter_quill/widgets/editor.dart';
import 'package:flutter_quill/widgets/toolbar.dart';
.....
....
...
QuillToolbar.basic(controller: quillController),
Expanded(
  child: Container(
    child: QuillEditor.basic(
      controller: quillController,
      readOnly: false, // true for view only mode
    ),
  ),
),
```
and their imports.

Also tried on empty project. Result is same.

Done before opening issue,
- Searched on Google
- Inspect on OpenSource code
- Readed Document well (over and over) ([Pub.dev](https://pub.dev/packages/flutter_quill), [Github](https://github.com/singerdmx/flutter-quill) )
- Tested on Empty Project (Android)
- Searched same issue on Github
- Try to change and fix to problem

Sorry, i cannot found any solution.
Thanks for any answer.
