### ISSUE TITLE
Can't use flutter_quill with extensions in the example

### ISSUE THREAD

**Issue by Vera-Spoettl** [singerdmx/flutter-quill#1501]
When I try to build the example from the current main branch, I get the following error message:

../flutter_quill_extensions/lib/embeds/toolbar/media_button.dart:350:38: Error: Member not found: 'oneLineRegExp'.
        !AutoFormatMultipleLinksRule.oneLineRegExp.hasMatch(value!)) {
                                     ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

My Flutter installlation:

[✓] Flutter (Channel stable, 3.13.7, on macOS 14.0 23A344 darwin-arm64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

pubspec.yaml of current example

```yaml
name: app
description: demo app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  filesystem_picker: ^4.0.0
  file_picker: ^6.0.0
  flutter_quill:
    path: ../
  flutter_quill_extensions:
    path: ../flutter_quill_extensions

dependency_overrides:
  flutter_quill:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: monospace
      fonts:
        - asset: assets/fonts/MonoSpace.ttf
    - family: serif
      fonts:
        - asset: assets/fonts/Serif.ttf
    - family: sans-serif
      fonts:
        - asset: assets/fonts/SansSerif.ttf
    - family: ibarra-real-nova
      fonts:
          - asset: assets/fonts/IbarraRealNova-Regular.ttf
    - family: square-peg
      fonts:
        - asset: assets/fonts/SquarePeg-Regular.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: roboto-mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: SF-UI-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
```
