### ISSUE TITLE
Using flutter_quill with integration_test is not possible

### ISSUE THREAD

**Issue by khainke** [singerdmx/flutter-quill#1502]
Imo, `integration_test` is a very basic flutter sdk dev dependency. Is there a way to relax the platform dependency of the flutter_quill package, so that flutter_quill at least works together with basic flutter sdk dependencies?

The problem: Every project with an `integration_test` dependency fails with a dependency conflict:

`pubspec.yaml`

```yaml
...

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

...

dependencies:
  flutter_quill: ^8.1.3

...

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

...
```

`flutter pub get` Output:

```
Resolving dependencies... (1.4s)
Note: platform is pinned to version 3.1.0 by flutter_driver from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because every version of integration_test from sdk depends on flutter_driver
  from sdk which depends on platform 3.1.0, every version of integration_test
  from sdk requires platform 3.1.0.
And because flutter_quill >=7.4.12 depends on platform ^3.1.3,
  integration_test from sdk is incompatible with flutter_quill >=7.4.12.
So, because project_name depends on both flutter_quill ^8.1.3 and
  integration_test from sdk, version solving failed.
```
