### ISSUE TITLE
Incompatible with current Flutter SDK.

### ISSUE THREAD

**Issue by SMH-Lily** [singerdmx/flutter-quill#1866]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

I would love to keep using this package, but the pub score is too low and the app has too many dependencies.

### Proposal

Please check the Score tab in pub.dev

![image](https://github.com/singerdmx/flutter-quill/assets/56062878/8c368288-92de-4144-a335-2f541c23aa95)

**Comment by ellet0** [comment]
It's probably an analysis issue from pub.dev side, for example, the issue tracker is already defined, see [this](https://github.com/singerdmx/flutter-quill/blob/9d84ef65439c93b4ee90ad1e8e5eddae587ad3d7/pubspec.yaml#L6) link

![image](https://github.com/singerdmx/flutter-quill/assets/73608287/95bea189-ab52-44ab-8efc-47aeba235bdd)

**Comment by romanr** [comment]
Better rename this issue to "**Incompatible with current Flutter SDK.**"
if you use intl, localizations, `pub get` unable to resolve;

> `Because every version of flutter_localizations from sdk depends on intl 0.19.0 and flutter_quill >=9.2.4 depends on intl ^0.18.1, flutter_localizations from sdk is incompatible with flutter_quill >=9.2.4.`
> `So, because depends on both flutter_quill ^9.3.11 and flutter_localizations from sdk, version solving failed.`

**Comment by Judimax** [comment]
if this helps I noticed that flutter_colorpicker on pub dev seems never to been updated but its github repo has the latest updates

**Comment by AlceoMazza** [comment]
While waiting for updates I'm having my project temporarily work by adding dependency overrides in my `pubspec.yaml`, like this:
```
dependency_overrides:
  flutter_colorpicker: # Keep this dependency override until flutter_colorpicker updates get published on pub.dev or until flutter_quill changes package for its color picker
    git: https://github.com/mchome/flutter_colorpicker.git
  intl: ^0.19.0 # Keep this dependency override until flutter_quill gets updated
```

**Comment by ellet0** [comment]
```yaml

dependency_overrides:
  # TODO: Temporarily add this to avoid build failure
  flutter_quill:
    git: https://github.com/singerdmx/flutter-quill.git
  flutter_colorpicker:
    git: https://github.com/mchome/flutter_colorpicker.git
  pdf_widget_wrapper: ^1.0.4

```

This should fix the issue as a temporary solution
