### ISSUE TITLE
 flutter_quill_extensions  is not working in android 

### ISSUE THREAD

**Issue by rashmi-key** [singerdmx/flutter-quill#2021]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Following pub version I'm using . We are not getting any error but not able to write anything . 
Below is the code snippet 

```dart
QuillRichTextEditor(
  width: double.infinity,
  padding: EdgeInsets.symmetric(
     horizontal: Sizes.L.getValue(),
     vertical: Sizes.S.getValue()),
  height: 180.0,
  borderColor: KeyTheme.of(context).borderColor,
  fontColor: KeyTheme.of(context).tertiaryText,
  borderWidth: 2.0,
  fontSize: 15.0,
  borderRadius: 12.0,
  hintText: StringConst.eventDescriptionHint,
  hintTextColor: KeyTheme.of(context).textHintColor,
  initialText: eventDescription,
  controller: quillControllerEventDesc,
  onValueChanged: (quillResult) async {},
)
 ```
                                
```yaml
  flutter_quill: 9.3.12
  dart_quill_delta: 9.3.21
  flutter_quill_extensions: 9.3.4
  flutter_quill_test: 9.3.4
  vsc_quill_delta_to_html: ^1.0.5
```
