### ISSUE TITLE
[Mobile] Errors with photo_view-0.11.1 and flutter_colorpicker-0.4.0

### ISSUE THREAD

**Issue by codesxt** [singerdmx/flutter-quill#284]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here.

I tried creating a basic project and I got errors related to photo_view and flutter_colorpicker plugins. I also got the same errors while building the example project for Android. The errors were the following:
 
```
bruno@keyblade:~/Desarrollo/notis/notisclient/flutter-quill/example$ flutter build apk
Running "flutter pub get" in example...                             7,8s

💪 Building with sound null safety 💪

../../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/photo_view-0.11.1/lib/src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../SDK/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../SDK/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^
../../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../SDK/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../SDK/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^


FAILURE: Build failed with an exception.

* Where:
Script '/home/bruno/Desarrollo/SDK/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1052

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/bruno/Desarrollo/SDK/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 48s
Running Gradle task 'assembleRelease'...                          109,0s
Gradle task assembleRelease failed with exit code 1
```

I'm on the master branch and this is my pubspec.yaml.

```
name: notisclient
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
```
