### ISSUE TITLE
[Mobile] can't use flutter_quill with flutter_inappwebview

### ISSUE THREAD

**Issue by amondnet** [singerdmx/flutter-quill#919]
My issue is about [Mobile]

I have tried running `example` directory successfully before creating an issue here. 

Please note that we are using <b>latest</b> flutter version in stable channel on branch master. If you are using beta or master channel, or you are not using <b>latest</b> flutter version in stable channel, you may experience error.

1. use `flutter_inappwebview` or package using `flutter_inappwebview`.
2. android - build error
    ```
    com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
    Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
    Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times:
    ```
3. ios - crash
    ```
    Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Duplicate 
    plugin key: InAppWebViewFlutterPlugin'
    ```

Because `flutter_inappwebview_quill` and `flutter_quill` has same package name and plugin key, we can't use `flutter_quill` with `flutter_inappwebview`.

**Comment by amondnet** [comment]
```
dependency_overrides:
  flutter_quill:
    git:
      url: https://github.com/balancefriends/flutter-quill.git
      ref: 5.4.1
  flutter_inappwebview:
    git:
      url: https://github.com/CodeEagle/flutter_inappwebview.git
      ref: 06f87e81c4f55b7b251a149ec0db60442bb351c3
```
