### ISSUE TITLE
BuildConfig is defined multiple times

### ISSUE THREAD

**Issue by GerJeffrey** [singerdmx/flutter-quill#939]
After I update my flutter to 3.0 then error happened:
ERROR:build/app/intermediates/transforms/APMSPlugin/release/119.jar: R8: Type com.pichillilorenzo.flutter_inappwebview.BuildConfig is defined multiple times: build/app/intermediates/transforms/APMSPlugin/release/119.jar:com/pichillilorenzo/flutter_inappwebview/BuildConfig.class, ycapp/build/app/intermediates/transforms/APMSPlugin/release/128.jar:com/pichillilorenzo/flutter_inappwebview/BuildConfig.class

I find in my pubspec.lock:
flutter_inappwebview:
dependency: transitive
description:
name: flutter_inappwebview
url: "https://pub.flutter-io.cn/"
source: hosted
version: "5.4.3+7"
flutter_inappwebview_quill:
dependency: transitive
description:
name: flutter_inappwebview_quill
url: "https://pub.flutter-io.cn/"
source: hosted
version: "5.4.6"

### And I check the flutter build intermediates BuildConfig
the two packages has the same package name:
package com.pichillilorenzo.flutter_inappwebview;

so conflicts happened.
How Do I Resolve This Problem, thanks!

**Comment by definitelyme** [comment]
Any update on this @singerdmx. R8 fails when building release apk

**Comment by singerdmx** [comment]
```
dependency_overrides:
  url_launcher: ^6.1.2
  http_parser: ">=4.0.0"
  plugin_platform_interface: ">=2.0.0"
  xml: ^5.0.0
  analyzer: ^3.0.0
  math_keyboard: ^0.1.6
  flutter_math_fork: ^0.6.3+1
  flutter_svg: ^1.1.6
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
```
